# coding: utf-8

"""
    bank-access-api

    This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_get(self):
        """Test case for authenticate_get

        authentication  # noqa: E501
        """
        pass

    def test_authorize_get(self):
        """Test case for authorize_get

        authorization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
