# coding: utf-8

# flake8: noqa
"""
    bank-access-api

    This is an example of using OAuth2 Access Code Flow in a specification to describe security to your API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.secret import Secret
